name: Deploy To EC2 for FitPet (using Environment Variables)

on:
  push:
    branches:
      - feature/meal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 빌드 (테스트 제외)
        run: ./gradlew clean build -x test

      - name: 빌드된 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./fitpet.jar

      - name: SCP로 EC2에 빌드 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: fitpet.jar
          target: /home/ubuntu/fitpet-server/tobe

      - name: EC2에서 환경변수 설정 및 배포 스크립트 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            export DB_URL="${{ secrets.DB_URL }}"
            export DB_USERNAME="${{ secrets.DB_USERNAME }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export SECURITY_USER="${{ secrets.SECURITY_USER }}"
            export SECURITY_PASSWORD="${{ secrets.SECURITY_PASSWORD }}"
            export JWT_ACCESS_SECRET="${{ secrets.JWT_ACCESS_SECRET }}"
            export JWT_REFRESH_SECRET="${{ secrets.JWT_REFRESH_SECRET }}"
            export JWT_ACCESS_EXPIRATION_MS="${{ secrets.JWT_ACCESS_EXPIRATION_MS }}"
            export JWT_REFRESH_EXPIRATION_MS="${{ secrets.JWT_REFRESH_EXPIRATION_MS }}"
            export GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}"
            export GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"
            export KAKAO_CLIENT_ID="${{ secrets.KAKAO_CLIENT_ID }}"

            rm -rf /home/ubuntu/fitpet-server/current
            mkdir -p /home/ubuntu/fitpet-server/current
            mv /home/ubuntu/fitpet-server/tobe/fitpet.jar /home/ubuntu/fitpet-server/current/fitpet.jar
            
            cd /home/ubuntu/fitpet-server/current
            
            sudo fuser -k -n tcp 8080 || true
            
            nohup java -jar fitpet.jar > ./output.log 2>&1 &